services:
  # Backend Application (Laravel)
  wte-backend:
    build:
      context: .
      dockerfile: .docker/php/prod.Dockerfile
    container_name: wte-backend
    restart: unless-stopped
    tty: true
    environment:
      - no_proxy=.wte-backend
    working_dir: /var/www
    volumes:
      - .:/var/www
      - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - wte-network
    depends_on:
      - wte-db

  # Backend Nginx (serving Laravel)
  wte-nginx-backend:
    image: nginx:latest
    container_name: wte-nginx-backend
    restart: unless-stopped
    ports:
      - "8080:80"  # Expose backend on port 8080 for debugging if needed
    volumes:
      - .:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - wte-network
    depends_on:
      - wte-backend

  # Database
  wte-db:
    image: postgres:latest
    container_name: wte-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - wte-db-data:/var/lib/postgresql/data
    networks:
      - wte-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Frontend (Quasar) served by Nginx
  wte-frontend:
    build:
      context: ../wte-frontend
      dockerfile: .docker/dockerfiles/prod.Dockerfile
    container_name: wte-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - wte-network

networks:
  wte-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.30.0.0/24"
          gateway: 172.30.0.1

volumes:
  wte-db-data:
    driver: local
