services:
    wte-app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: wte-app
        restart: unless-stopped
        tty: true
        environment:
            - no_proxy=.wte-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            wte-app-network:
        depends_on:
            - wte-db

    wte-nginx:
        image: nginx:latest
        container_name: wte-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - .docker/nginx:/etc/nginx/conf.d
        networks:
            wte-app-network:
        depends_on:
            - wte-app

    wte-db:
        image: postgres:latest
        container_name: wte-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - wte-db-data:/var/lib/postgresql/data
        networks:
            wte-app-network:
                ipv4_address: 172.22.0.2
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

networks:
    wte-app-network:
        driver: bridge
        ipam:
            config:
                - subnet: "172.22.0.0/24"
                  gateway: 172.22.0.1

volumes:
    wte-db-data:
        driver: local
